# Generated by Django 4.0.3 on 2022-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('user_name', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=9)),
                ('designation', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
        ),
    ]
